### ISSUE TITLE
Chromedriver version is out of date

### ISSUE THREAD

**Issue by kierans** [fleg/nw-chromedriver#1]
@fleg If you're not interested in maintaining the project can you transfer it to me?

**Comment by fleg** [comment]
Added you to collaborators.
Can you provide your npm username, so I can add you to maintainers?

**Comment by kierans** [comment]
kierans777

**Comment by fleg** [comment]
done

**Comment by kierans** [comment]
I believe this can be closed due to later versions  of `nw-chromedriver` now available.
