### ISSUE TITLE
Centralised download location

### ISSUE THREAD

**Issue by insightfuls** [fleg/nw-chromedriver#4]
Suggestion/enhancement request: could the downloaded binary go in a central cache (i.e. in a dot-directory in the user's home directory) so that if you install the module in multiple projects or blow away your node_modules it doesn't have to download the binary again?

(Hoping we can get a similar change to nwjs-builder-phoenix as well.)

**Comment by kierans** [comment]
This was published as part of `nw-chromedriver-installer@1.1.0`
